### ISSUE TITLE
vaapi support ?

### ISSUE THREAD

**Issue by MatMaul** [UnitedRPMs/chromium-freeworld#5]
What do you think about enabling vaapi support ?
https://aur.archlinux.org/cgit/aur.git/tree/chromium-vaapi-r12.patch?h=chromium-vaapi

**Comment by kuboosoft** [comment]
@MatMaul The patch is a great idea; but I can't maintain it (I don't have time), to rhythm of chromium ( hard debug and test), I am maintaining chromium-freeworld  and is a hard job and other hard packages; if you co-maintain it, welcome. But our chromium-freeworld is a stable branch  for our users. Solution if you have the know for to patch it constantly and test constantly we can merge. I removed vaapi patch because it broke rendering on non-intel cards.

**Comment by MatMaul** [comment]
Ok thanks I understand. I don't feel like co-maintaining right now, especially since it takes me hours to compile on my laptop...

**Comment by kuboosoft** [comment]
@MatMaul 

> especially since it takes me hours to compile on my laptop

I have the same situation... Imagine constants updates... (8-18 hours and 4 fedora versions)

**Comment by kuboosoft** [comment]
@MatMaul Now our chromium-freeworld enables vaapi, enjoy!
